### ISSUE TITLE
docker hub page not found 404 on bitnami/elasticsearch-curator

### ISSUE THREAD

**Issue by IdeoG** [lebenitza/charts#17]
Hi, We faced with an issue that we can't pull the image from https://hub.docker.com/r/bitnami/elasticsearch-curator. 
Was something changed?

**Comment by devops-cafex** [comment]
We have hit the same issue looks like its been depreciated

https://github.com/bitnami/containers/blob/116ec7ab66b1701641a8103196d09d98dc9863df/bitnami/elasticsearch-curator/README.md

Guess override the image in the local values file to one self hosted or move to another image in the chart

**Comment by terrpan** [comment]
I did the following updates to the values to get it to work.

I switched to the image that ES are referring to in their [docs](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/docker.html)

I added this to our values.yaml
```yaml
image:
  repository: untergeek/curator
  tag: 7.0.0 # <-- Check the tags in the repo. Apparently they are major version locked.

command: ["curator/curator"] # <-- path to binary.
```
